include(${CGET_CORE_DIR}.cget/core.cmake)

CGET_HAS_DEPENDENCY(RapidJSON GITHUB miloyip/rapidjson VERSION v1.0.2
  OPTIONS "-DRAPIDJSON_BUILD_TESTS=OFF -DRAPIDJSON_BUILD_DOC=OFF -DRAPIDJSON_BUILD_EXAMPLES=OFF")

CGET_HAS_DEPENDENCY(gflags GITHUB gflags/gflags VERSION v2.1.2)
CGET_HAS_DEPENDENCY(CURL REGISTRY VERSION master)

