if(NOT CGET_CORE_DIR)
    set(CGET_CORE_DIR "${CMAKE_SOURCE_DIR}")
endif()

include("${CGET_CORE_DIR}/.cget/core.cmake" REQUIRED)

CGET_HAS_DEPENDENCY(RapidJSON GITHUB miloyip/rapidjson VERSION v1.0.2
  OPTIONS "-DRAPIDJSON_BUILD_TESTS=OFF -DRAPIDJSON_BUILD_DOC=OFF -DRAPIDJSON_BUILD_EXAMPLES=OFF")

CGET_HAS_DEPENDENCY(gflags GITHUB gflags/gflags VERSION v2.2.0)
CGET_HAS_DEPENDENCY(CURL REGISTRY VERSION master)

